export const GET_CATORY_SUCCESS = 'GET_CATORY_SUCCESS';
export const GET_CATORY_FAILURE = 'GET_CATORY_FAILURE';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';