export const GET_CATORY_SUCCESS = 'GET_CATORY_SUCCESS';
export const GET_CATORY_FAILURE = 'GET_CATORY_FAILURE';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const LOGOUT = 'LOGOUT';

export const ADD_CART = 'ADD_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const EMPTY_CART = 'EMPTY_CART';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const REMOVE_ERROR = 'REMOVE_ERROR';